_wandb:
    value:
        cli_version: 0.21.1
        e:
            s53cfjoaub4lmp9rfrrp37nj1q1uc3cd:
                args:
                    - --per_device_train_batch_size
                    - "8"
                    - --per_device_eval_batch_size
                    - "16"
                    - --num_train_epochs
                    - "3"
                    - --learning_rate
                    - "5e-5"
                    - --eval_steps
                    - "100"
                    - --logging_steps
                    - "50"
                    - --save_steps
                    - "500"
                    - --lr_scheduler_type
                    - linear
                    - --gradient_accumulation_steps
                    - "1"
                    - --num_train_samples
                    - "6000"
                    - --num_eval_samples
                    - "100"
                    - --report_to
                    - wandb
                    - --hp_search
                codePath: byteformer-hf-migration\scripts\train_hf_trainer_with_search.py
                codePathLocal: byteformer-hf-migration\scripts\train_hf_trainer_with_search.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "499774386176"
                        used: "240261177344"
                email: yellow_person@outlook.com
                executable: D:\MLLMs\MLLM\.venv\Scripts\python.exe
                git:
                    commit: 1aa3acd17b7b02ba51889b648b1182845c4323eb
                    remote: https://github.com/apple/corenet.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-25d77015-9bd7-8fa9-24f8-7773aa31d4d4
                host: PC-YPFREE
                memory:
                    total: "16849256448"
                os: Windows-11-10.0.26100-SP0
                program: D:\MLLMs\corenet\byteformer-hf-migration\scripts\train_hf_trainer_with_search.py
                python: CPython 3.12.10
                root: D:\MLLMs\corenet
                startedAt: "2025-08-14T08:57:45.101847Z"
                writerId: s53cfjoaub4lmp9rfrrp37nj1q1uc3cd
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 2
                - 14
            "4": 3.12.10
            "5": 0.21.1
            "6": 4.54.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
learning_rate:
    value: 0.0001468487174436464
metric:
    value: eval/loss
num_train_epochs:
    value: 5
per_device_train_batch_size:
    value: 16
warmup_ratio:
    value: 0.04860948371615895
