_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
                - 105
            "2":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
                - 100
                - 105
            "3":
                - 23
                - 55
                - 61
            "4": 3.12.3
            "5": 0.19.10
            "6": 4.55.0
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
