_wandb:
    value:
        cli_version: 0.21.1
        e:
            cm9do58l8sb615x3653o4g9va26s7r4c:
                args:
                    - --per_device_train_batch_size
                    - "8"
                    - --per_device_eval_batch_size
                    - "16"
                    - --num_train_epochs
                    - "3"
                    - --learning_rate
                    - "5e-5"
                    - --eval_steps
                    - "100"
                    - --logging_steps
                    - "50"
                    - --save_steps
                    - "500"
                    - --lr_scheduler_type
                    - linear
                    - --gradient_accumulation_steps
                    - "1"
                    - --num_train_samples
                    - "6000"
                    - --num_eval_samples
                    - "100"
                    - --report_to
                    - wandb
                    - --hp_search
                codePath: byteformer-hf-migration\scripts\train_hf_trainer_with_search.py
                codePathLocal: byteformer-hf-migration\scripts\train_hf_trainer_with_search.py
                email: yellow_person@outlook.com
                executable: D:\MLLMs\MLLM\.venv\Scripts\python.exe
                git:
                    commit: 1aa3acd17b7b02ba51889b648b1182845c4323eb
                    remote: https://github.com/apple/corenet.git
                host: PC-YPFREE
                os: Windows-11-10.0.26100-SP0
                program: D:\MLLMs\corenet\byteformer-hf-migration\scripts\train_hf_trainer_with_search.py
                python: CPython 3.12.10
                root: D:\MLLMs\corenet
                startedAt: "2025-08-14T08:34:48.947068Z"
                writerId: cm9do58l8sb615x3653o4g9va26s7r4c
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 2
                - 14
            "4": 3.12.10
            "5": 0.21.1
            "6": 4.54.1
            "8":
                - 3
            "12": 0.21.1
            "13": windows-amd64
learning_rate:
    value: 7.073040467897757e-05
metric:
    value: eval/loss
num_train_epochs:
    value: 4
per_device_train_batch_size:
    value: 8
warmup_ratio:
    value: 0.1900893559567977
